// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChAvb0igkR7jB7t1TAgU4ocHfHhEBYU0s',
    appId: '1:24974446130:web:925fca71114f8e5fa0b62b',
    messagingSenderId: '24974446130',
    projectId: 'studymentor-cu',
    authDomain: 'studymentor-cu.firebaseapp.com',
    storageBucket: 'studymentor-cu.firebasestorage.app',
    measurementId: 'G-144J7Y49FG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA4G51Z6xdBq_v0qifARlqOz2Aszb1RZI',
    appId: '1:24974446130:android:2c927cc98551d6faa0b62b',
    messagingSenderId: '24974446130',
    projectId: 'studymentor-cu',
    storageBucket: 'studymentor-cu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD78i0AHH9A2cQC6xeNu3TrwZvCj502dAo',
    appId: '1:24974446130:ios:e40b61f69f5bac0ea0b62b',
    messagingSenderId: '24974446130',
    projectId: 'studymentor-cu',
    storageBucket: 'studymentor-cu.firebasestorage.app',
    iosBundleId: 'com.example.studymentor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD78i0AHH9A2cQC6xeNu3TrwZvCj502dAo',
    appId: '1:24974446130:ios:e40b61f69f5bac0ea0b62b',
    messagingSenderId: '24974446130',
    projectId: 'studymentor-cu',
    storageBucket: 'studymentor-cu.firebasestorage.app',
    iosBundleId: 'com.example.studymentor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChAvb0igkR7jB7t1TAgU4ocHfHhEBYU0s',
    appId: '1:24974446130:web:28348518e44a0cf4a0b62b',
    messagingSenderId: '24974446130',
    projectId: 'studymentor-cu',
    authDomain: 'studymentor-cu.firebaseapp.com',
    storageBucket: 'studymentor-cu.firebasestorage.app',
    measurementId: 'G-6M2PP0RMG5',
  );

}