// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfdzHRIGMGBAen1RHPDq7jaqx2RQYbNW8',
    appId: '1:546676894438:web:ddb97d19877360c10ba927',
    messagingSenderId: '546676894438',
    projectId: 'fcai-studymentor',
    authDomain: 'fcai-studymentor.firebaseapp.com',
    storageBucket: 'fcai-studymentor.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6MRFekWzbpyNZeqQiHrkgHsfRSQNoPAA',
    appId: '1:546676894438:android:4b12802b89e9e02a0ba927',
    messagingSenderId: '546676894438',
    projectId: 'fcai-studymentor',
    storageBucket: 'fcai-studymentor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeLsOH5IPfQEpxzNVuzhM6xVxprD2Z9z0',
    appId: '1:546676894438:ios:a87ba8d55cbb964f0ba927',
    messagingSenderId: '546676894438',
    projectId: 'fcai-studymentor',
    storageBucket: 'fcai-studymentor.firebasestorage.app',
    iosBundleId: 'com.example.studymentor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeLsOH5IPfQEpxzNVuzhM6xVxprD2Z9z0',
    appId: '1:546676894438:ios:a87ba8d55cbb964f0ba927',
    messagingSenderId: '546676894438',
    projectId: 'fcai-studymentor',
    storageBucket: 'fcai-studymentor.firebasestorage.app',
    iosBundleId: 'com.example.studymentor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfdzHRIGMGBAen1RHPDq7jaqx2RQYbNW8',
    appId: '1:546676894438:web:1bb2f14bef4db4d70ba927',
    messagingSenderId: '546676894438',
    projectId: 'fcai-studymentor',
    authDomain: 'fcai-studymentor.firebaseapp.com',
    storageBucket: 'fcai-studymentor.firebasestorage.app',
  );
}
