// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAymlhEPYxJoXMmh5MsqrluC1RTr6106A',
    appId: '1:606117093250:web:5d62f64a9bb3b0d4ccb99b',
    messagingSenderId: '606117093250',
    projectId: 'studymentor-2026',
    authDomain: 'studymentor-2026.firebaseapp.com',
    storageBucket: 'studymentor-2026.firebasestorage.app',
    measurementId: 'G-820JR0QRLW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7rfgZesBgbnAChK8HapnolSykXRRp98I',
    appId: '1:606117093250:android:9636ccda2d7e1bddccb99b',
    messagingSenderId: '606117093250',
    projectId: 'studymentor-2026',
    storageBucket: 'studymentor-2026.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZjINgl6z4kZ-0p-jvlkaS_TLkaCDmFQk',
    appId: '1:606117093250:ios:c813d962959abc21ccb99b',
    messagingSenderId: '606117093250',
    projectId: 'studymentor-2026',
    storageBucket: 'studymentor-2026.firebasestorage.app',
    iosBundleId: 'com.example.studymentor',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZjINgl6z4kZ-0p-jvlkaS_TLkaCDmFQk',
    appId: '1:606117093250:ios:c813d962959abc21ccb99b',
    messagingSenderId: '606117093250',
    projectId: 'studymentor-2026',
    storageBucket: 'studymentor-2026.firebasestorage.app',
    iosBundleId: 'com.example.studymentor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAymlhEPYxJoXMmh5MsqrluC1RTr6106A',
    appId: '1:606117093250:web:39b31477394a9eb1ccb99b',
    messagingSenderId: '606117093250',
    projectId: 'studymentor-2026',
    authDomain: 'studymentor-2026.firebaseapp.com',
    storageBucket: 'studymentor-2026.firebasestorage.app',
    measurementId: 'G-Z8HZR0M6RQ',
  );
}
