mutation InsertUser($email: String!, $fullName: String!, $role: Role!) @auth(level: USER) {
  user_insert(
    data: {
      uid_expr: "auth.uid"
      email: $email
      fullName: $fullName
      role: $role
      isActive: true
    }
  )
}

mutation UpsertCurrentUser($email: String!, $fullName: String, $role: Role!) @auth(level: USER) {
  user_upsert(
    data: {
      uid_expr: "auth.uid"
      email: $email
      fullName: $fullName
      role: $role
    }
  )
}

mutation DeleteUser @auth(level: USER) {
  user_delete(key: { uid_expr: "auth.uid" })
}