query ListUsers @auth(level: NO_ACCESS) {
  users {
    uid
    email
    fullName
    role
    isActive
    createdAt
  }
}

query GetUserByUid($uid: String!) @auth(level: USER) {
  user(key: { uid: $uid }) {
    uid
    email
    fullName
    role
    isActive
    createdAt
  }
}