extend type Mutation {
  """
  ✨ Insert a single `AppRule` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  appRule_insert(
    """
    Data object to insert into the table.
    """
    data: AppRule_Data!
  ): AppRule_KeyOutput! @fdc_generated(from: "AppRule", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `InstalledApp` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  installedApp_insert(
    """
    Data object to insert into the table.
    """
    data: InstalledApp_Data!
  ): InstalledApp_KeyOutput! @fdc_generated(from: "InstalledApp", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Parent` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  parent_insert(
    """
    Data object to insert into the table.
    """
    data: Parent_Data!
  ): Parent_KeyOutput! @fdc_generated(from: "Parent", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Student` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  student_insert(
    """
    Data object to insert into the table.
    """
    data: Student_Data!
  ): Student_KeyOutput! @fdc_generated(from: "Student", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `StudentAvatar` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  studentAvatar_insert(
    """
    Data object to insert into the table.
    """
    data: StudentAvatar_Data!
  ): StudentAvatar_KeyOutput! @fdc_generated(from: "StudentAvatar", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `StudentConfig` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  studentConfig_insert(
    """
    Data object to insert into the table.
    """
    data: StudentConfig_Data!
  ): StudentConfig_KeyOutput! @fdc_generated(from: "StudentConfig", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `StudentOwnedItem` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  studentOwnedItem_insert(
    """
    Data object to insert into the table.
    """
    data: StudentOwnedItem_Data!
  ): StudentOwnedItem_KeyOutput! @fdc_generated(from: "StudentOwnedItem", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `StudentSettings` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  studentSettings_insert(
    """
    Data object to insert into the table.
    """
    data: StudentSettings_Data!
  ): StudentSettings_KeyOutput! @fdc_generated(from: "StudentSettings", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `SubjectProgress` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  subjectProgress_insert(
    """
    Data object to insert into the table.
    """
    data: SubjectProgress_Data!
  ): SubjectProgress_KeyOutput! @fdc_generated(from: "SubjectProgress", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `SupportTicket` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  supportTicket_insert(
    """
    Data object to insert into the table.
    """
    data: SupportTicket_Data!
  ): SupportTicket_KeyOutput! @fdc_generated(from: "SupportTicket", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `User` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  user_insert(
    """
    Data object to insert into the table.
    """
    data: User_Data!
  ): User_KeyOutput! @fdc_generated(from: "User", purpose: INSERT_SINGLE)
  """
  ✨ Insert `AppRule` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  appRule_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [AppRule_Data!]!
  ): [AppRule_KeyOutput!]! @fdc_generated(from: "AppRule", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `InstalledApp` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  installedApp_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [InstalledApp_Data!]!
  ): [InstalledApp_KeyOutput!]! @fdc_generated(from: "InstalledApp", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Parent` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  parent_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Parent_Data!]!
  ): [Parent_KeyOutput!]! @fdc_generated(from: "Parent", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Student` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  student_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Student_Data!]!
  ): [Student_KeyOutput!]! @fdc_generated(from: "Student", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `StudentAvatar` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  studentAvatar_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [StudentAvatar_Data!]!
  ): [StudentAvatar_KeyOutput!]! @fdc_generated(from: "StudentAvatar", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `StudentConfig` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  studentConfig_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [StudentConfig_Data!]!
  ): [StudentConfig_KeyOutput!]! @fdc_generated(from: "StudentConfig", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `StudentOwnedItem` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  studentOwnedItem_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [StudentOwnedItem_Data!]!
  ): [StudentOwnedItem_KeyOutput!]! @fdc_generated(from: "StudentOwnedItem", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `StudentSettings` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  studentSettings_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [StudentSettings_Data!]!
  ): [StudentSettings_KeyOutput!]! @fdc_generated(from: "StudentSettings", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `SubjectProgress` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  subjectProgress_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [SubjectProgress_Data!]!
  ): [SubjectProgress_KeyOutput!]! @fdc_generated(from: "SubjectProgress", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `SupportTicket` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  supportTicket_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [SupportTicket_Data!]!
  ): [SupportTicket_KeyOutput!]! @fdc_generated(from: "SupportTicket", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `User` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  user_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [User_Data!]!
  ): [User_KeyOutput!]! @fdc_generated(from: "User", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert or update a single `AppRule` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `AppRule`.
  """
  appRule_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: AppRule_Data!
  ): AppRule_KeyOutput! @fdc_generated(from: "AppRule", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `InstalledApp` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `InstalledApp`.
  """
  installedApp_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: InstalledApp_Data!
  ): InstalledApp_KeyOutput! @fdc_generated(from: "InstalledApp", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Parent` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Parent`.
  """
  parent_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Parent_Data!
  ): Parent_KeyOutput! @fdc_generated(from: "Parent", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Student` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Student`.
  """
  student_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Student_Data!
  ): Student_KeyOutput! @fdc_generated(from: "Student", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `StudentAvatar` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `StudentAvatar`.
  """
  studentAvatar_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: StudentAvatar_Data!
  ): StudentAvatar_KeyOutput! @fdc_generated(from: "StudentAvatar", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `StudentConfig` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `StudentConfig`.
  """
  studentConfig_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: StudentConfig_Data!
  ): StudentConfig_KeyOutput! @fdc_generated(from: "StudentConfig", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `StudentOwnedItem` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `StudentOwnedItem`.
  """
  studentOwnedItem_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: StudentOwnedItem_Data!
  ): StudentOwnedItem_KeyOutput! @fdc_generated(from: "StudentOwnedItem", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `StudentSettings` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `StudentSettings`.
  """
  studentSettings_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: StudentSettings_Data!
  ): StudentSettings_KeyOutput! @fdc_generated(from: "StudentSettings", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `SubjectProgress` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `SubjectProgress`.
  """
  subjectProgress_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: SubjectProgress_Data!
  ): SubjectProgress_KeyOutput! @fdc_generated(from: "SubjectProgress", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `SupportTicket` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `SupportTicket`.
  """
  supportTicket_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: SupportTicket_Data!
  ): SupportTicket_KeyOutput! @fdc_generated(from: "SupportTicket", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `User` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `User`.
  """
  user_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: User_Data!
  ): User_KeyOutput! @fdc_generated(from: "User", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update `AppRule` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `AppRule`.
  """
  appRule_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [AppRule_Data!]!
  ): [AppRule_KeyOutput!]! @fdc_generated(from: "AppRule", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `InstalledApp` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `InstalledApp`.
  """
  installedApp_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [InstalledApp_Data!]!
  ): [InstalledApp_KeyOutput!]! @fdc_generated(from: "InstalledApp", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Parent` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Parent`.
  """
  parent_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Parent_Data!]!
  ): [Parent_KeyOutput!]! @fdc_generated(from: "Parent", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Student` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Student`.
  """
  student_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Student_Data!]!
  ): [Student_KeyOutput!]! @fdc_generated(from: "Student", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `StudentAvatar` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `StudentAvatar`.
  """
  studentAvatar_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [StudentAvatar_Data!]!
  ): [StudentAvatar_KeyOutput!]! @fdc_generated(from: "StudentAvatar", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `StudentConfig` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `StudentConfig`.
  """
  studentConfig_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [StudentConfig_Data!]!
  ): [StudentConfig_KeyOutput!]! @fdc_generated(from: "StudentConfig", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `StudentOwnedItem` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `StudentOwnedItem`.
  """
  studentOwnedItem_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [StudentOwnedItem_Data!]!
  ): [StudentOwnedItem_KeyOutput!]! @fdc_generated(from: "StudentOwnedItem", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `StudentSettings` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `StudentSettings`.
  """
  studentSettings_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [StudentSettings_Data!]!
  ): [StudentSettings_KeyOutput!]! @fdc_generated(from: "StudentSettings", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `SubjectProgress` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `SubjectProgress`.
  """
  subjectProgress_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [SubjectProgress_Data!]!
  ): [SubjectProgress_KeyOutput!]! @fdc_generated(from: "SubjectProgress", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `SupportTicket` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `SupportTicket`.
  """
  supportTicket_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [SupportTicket_Data!]!
  ): [SupportTicket_KeyOutput!]! @fdc_generated(from: "SupportTicket", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `User` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `User`.
  """
  user_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [User_Data!]!
  ): [User_KeyOutput!]! @fdc_generated(from: "User", purpose: UPSERT_MULTIPLE)
  """
  ✨ Update a single `AppRule` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `AppRule` or `null` if not found.
  """
  appRule_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: AppRule_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: AppRule_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: AppRule_Data!
  ): AppRule_KeyOutput @fdc_generated(from: "AppRule", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `InstalledApp` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `InstalledApp` or `null` if not found.
  """
  installedApp_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: InstalledApp_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: InstalledApp_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: InstalledApp_Data!
  ): InstalledApp_KeyOutput @fdc_generated(from: "InstalledApp", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Parent` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Parent` or `null` if not found.
  """
  parent_update(
    """
    The key used to identify the object.
    """
    key: Parent_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Parent_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Parent_Data!
  ): Parent_KeyOutput @fdc_generated(from: "Parent", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Student` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Student` or `null` if not found.
  """
  student_update(
    """
    The key used to identify the object.
    """
    key: Student_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Student_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Student_Data!
  ): Student_KeyOutput @fdc_generated(from: "Student", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `StudentAvatar` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `StudentAvatar` or `null` if not found.
  """
  studentAvatar_update(
    """
    The key used to identify the object.
    """
    key: StudentAvatar_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: StudentAvatar_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: StudentAvatar_Data!
  ): StudentAvatar_KeyOutput @fdc_generated(from: "StudentAvatar", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `StudentConfig` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `StudentConfig` or `null` if not found.
  """
  studentConfig_update(
    """
    The key used to identify the object.
    """
    key: StudentConfig_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: StudentConfig_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: StudentConfig_Data!
  ): StudentConfig_KeyOutput @fdc_generated(from: "StudentConfig", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `StudentOwnedItem` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `StudentOwnedItem` or `null` if not found.
  """
  studentOwnedItem_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: StudentOwnedItem_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: StudentOwnedItem_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: StudentOwnedItem_Data!
  ): StudentOwnedItem_KeyOutput @fdc_generated(from: "StudentOwnedItem", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `StudentSettings` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `StudentSettings` or `null` if not found.
  """
  studentSettings_update(
    """
    The key used to identify the object.
    """
    key: StudentSettings_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: StudentSettings_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: StudentSettings_Data!
  ): StudentSettings_KeyOutput @fdc_generated(from: "StudentSettings", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `SubjectProgress` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `SubjectProgress` or `null` if not found.
  """
  subjectProgress_update(
    """
    The key used to identify the object.
    """
    key: SubjectProgress_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: SubjectProgress_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: SubjectProgress_Data!
  ): SubjectProgress_KeyOutput @fdc_generated(from: "SubjectProgress", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `SupportTicket` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `SupportTicket` or `null` if not found.
  """
  supportTicket_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: SupportTicket_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: SupportTicket_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: SupportTicket_Data!
  ): SupportTicket_KeyOutput @fdc_generated(from: "SupportTicket", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `User` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `User` or `null` if not found.
  """
  user_update(
    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: User_Data!
  ): User_KeyOutput @fdc_generated(from: "User", purpose: UPDATE_SINGLE)
  """
  ✨ Update `AppRule` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  appRule_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: AppRule_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: AppRule_Data!
  ): Int! @fdc_generated(from: "AppRule", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `InstalledApp` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  installedApp_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: InstalledApp_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: InstalledApp_Data!
  ): Int! @fdc_generated(from: "InstalledApp", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Parent` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  parent_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Parent_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Parent_Data!
  ): Int! @fdc_generated(from: "Parent", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Student` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  student_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Student_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Student_Data!
  ): Int! @fdc_generated(from: "Student", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `StudentAvatar` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  studentAvatar_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: StudentAvatar_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: StudentAvatar_Data!
  ): Int! @fdc_generated(from: "StudentAvatar", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `StudentConfig` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  studentConfig_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: StudentConfig_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: StudentConfig_Data!
  ): Int! @fdc_generated(from: "StudentConfig", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `StudentOwnedItem` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  studentOwnedItem_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: StudentOwnedItem_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: StudentOwnedItem_Data!
  ): Int! @fdc_generated(from: "StudentOwnedItem", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `StudentSettings` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  studentSettings_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: StudentSettings_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: StudentSettings_Data!
  ): Int! @fdc_generated(from: "StudentSettings", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `SubjectProgress` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  subjectProgress_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: SubjectProgress_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: SubjectProgress_Data!
  ): Int! @fdc_generated(from: "SubjectProgress", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `SupportTicket` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  supportTicket_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: SupportTicket_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: SupportTicket_Data!
  ): Int! @fdc_generated(from: "SupportTicket", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `User` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  user_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: User_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: User_Data!
  ): Int! @fdc_generated(from: "User", purpose: UPDATE_MULTIPLE)
  """
  ✨ Delete a single `AppRule` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  appRule_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: AppRule_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: AppRule_FirstRow
  ): AppRule_KeyOutput @fdc_generated(from: "AppRule", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `InstalledApp` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  installedApp_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: InstalledApp_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: InstalledApp_FirstRow
  ): InstalledApp_KeyOutput @fdc_generated(from: "InstalledApp", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Parent` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  parent_delete(
    """
    The key used to identify the object.
    """
    key: Parent_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Parent_FirstRow
  ): Parent_KeyOutput @fdc_generated(from: "Parent", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Student` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  student_delete(
    """
    The key used to identify the object.
    """
    key: Student_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Student_FirstRow
  ): Student_KeyOutput @fdc_generated(from: "Student", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `StudentAvatar` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  studentAvatar_delete(
    """
    The key used to identify the object.
    """
    key: StudentAvatar_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: StudentAvatar_FirstRow
  ): StudentAvatar_KeyOutput @fdc_generated(from: "StudentAvatar", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `StudentConfig` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  studentConfig_delete(
    """
    The key used to identify the object.
    """
    key: StudentConfig_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: StudentConfig_FirstRow
  ): StudentConfig_KeyOutput @fdc_generated(from: "StudentConfig", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `StudentOwnedItem` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  studentOwnedItem_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: StudentOwnedItem_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: StudentOwnedItem_FirstRow
  ): StudentOwnedItem_KeyOutput @fdc_generated(from: "StudentOwnedItem", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `StudentSettings` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  studentSettings_delete(
    """
    The key used to identify the object.
    """
    key: StudentSettings_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: StudentSettings_FirstRow
  ): StudentSettings_KeyOutput @fdc_generated(from: "StudentSettings", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `SubjectProgress` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  subjectProgress_delete(
    """
    The key used to identify the object.
    """
    key: SubjectProgress_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: SubjectProgress_FirstRow
  ): SubjectProgress_KeyOutput @fdc_generated(from: "SubjectProgress", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `SupportTicket` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  supportTicket_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: SupportTicket_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: SupportTicket_FirstRow
  ): SupportTicket_KeyOutput @fdc_generated(from: "SupportTicket", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `User` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  user_delete(
    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User_KeyOutput @fdc_generated(from: "User", purpose: DELETE_SINGLE)
  """
  ✨ Delete `AppRule` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  appRule_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: AppRule_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "AppRule", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `InstalledApp` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  installedApp_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: InstalledApp_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "InstalledApp", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Parent` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  parent_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Parent_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Parent", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Student` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  student_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Student_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Student", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `StudentAvatar` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  studentAvatar_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: StudentAvatar_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "StudentAvatar", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `StudentConfig` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  studentConfig_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: StudentConfig_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "StudentConfig", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `StudentOwnedItem` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  studentOwnedItem_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: StudentOwnedItem_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "StudentOwnedItem", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `StudentSettings` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  studentSettings_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: StudentSettings_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "StudentSettings", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `SubjectProgress` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  subjectProgress_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: SubjectProgress_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "SubjectProgress", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `SupportTicket` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  supportTicket_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: SupportTicket_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "SupportTicket", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `User` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  user_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: User_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "User", purpose: DELETE_MULTIPLE)
}
