extend type Query {
  """
  ✨ Look up a single `AppRule` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  appRule(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: AppRule_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: AppRule_FirstRow
  ): AppRule @fdc_generated(from: "AppRule", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `InstalledApp` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  installedApp(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: InstalledApp_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: InstalledApp_FirstRow
  ): InstalledApp @fdc_generated(from: "InstalledApp", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Parent` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  parent(
    """
    The key used to identify the object.
    """
    key: Parent_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Parent_FirstRow
  ): Parent @fdc_generated(from: "Parent", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Student` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  student(
    """
    The key used to identify the object.
    """
    key: Student_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Student_FirstRow
  ): Student @fdc_generated(from: "Student", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `User` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  user(
    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User @fdc_generated(from: "User", purpose: QUERY_SINGLE)
  """
  ✨ List `AppRule` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  appRules(
    """
    Filter condition to narrow down the query results.
    """
    where: AppRule_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [AppRule_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: AppRule_Having
  ): [AppRule!]! @fdc_generated(from: "AppRule", purpose: QUERY_MULTIPLE)
  """
  ✨ List `InstalledApp` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  installedApps(
    """
    Filter condition to narrow down the query results.
    """
    where: InstalledApp_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [InstalledApp_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: InstalledApp_Having
  ): [InstalledApp!]! @fdc_generated(from: "InstalledApp", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Parent` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  parents(
    """
    Filter condition to narrow down the query results.
    """
    where: Parent_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Parent_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Parent_Having
  ): [Parent!]! @fdc_generated(from: "Parent", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Student` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  students(
    """
    Filter condition to narrow down the query results.
    """
    where: Student_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Student_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Student_Having
  ): [Student!]! @fdc_generated(from: "Student", purpose: QUERY_MULTIPLE)
  """
  ✨ List `User` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  users(
    """
    Filter condition to narrow down the query results.
    """
    where: User_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [User_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: User_Having
  ): [User!]! @fdc_generated(from: "User", purpose: QUERY_MULTIPLE)
}
