extend type Query {
  """
  ✨ Look up a single `AppRule` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  appRule(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: AppRule_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: AppRule_FirstRow
  ): AppRule @fdc_generated(from: "AppRule", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `FriendRequest` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  friendRequest(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: FriendRequest_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: FriendRequest_FirstRow
  ): FriendRequest @fdc_generated(from: "FriendRequest", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Friendship` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  friendship(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Friendship_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Friendship_FirstRow
  ): Friendship @fdc_generated(from: "Friendship", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `InstalledApp` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  installedApp(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: InstalledApp_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: InstalledApp_FirstRow
  ): InstalledApp @fdc_generated(from: "InstalledApp", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Parent` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  parent(
    """
    The key used to identify the object.
    """
    key: Parent_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Parent_FirstRow
  ): Parent @fdc_generated(from: "Parent", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Student` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  student(
    """
    The key used to identify the object.
    """
    key: Student_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Student_FirstRow
  ): Student @fdc_generated(from: "Student", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `StudentAvatar` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  studentAvatar(
    """
    The key used to identify the object.
    """
    key: StudentAvatar_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: StudentAvatar_FirstRow
  ): StudentAvatar @fdc_generated(from: "StudentAvatar", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `StudentConfig` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  studentConfig(
    """
    The key used to identify the object.
    """
    key: StudentConfig_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: StudentConfig_FirstRow
  ): StudentConfig @fdc_generated(from: "StudentConfig", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `StudentOwnedItem` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  studentOwnedItem(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: StudentOwnedItem_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: StudentOwnedItem_FirstRow
  ): StudentOwnedItem @fdc_generated(from: "StudentOwnedItem", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `StudentSettings` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  studentSettings(
    """
    The key used to identify the object.
    """
    key: StudentSettings_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: StudentSettings_FirstRow
  ): StudentSettings @fdc_generated(from: "StudentSettings", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `SubjectProgress` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  subjectProgress(
    """
    The key used to identify the object.
    """
    key: SubjectProgress_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: SubjectProgress_FirstRow
  ): SubjectProgress @fdc_generated(from: "SubjectProgress", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `SupportTicket` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  supportTicket(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: SupportTicket_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: SupportTicket_FirstRow
  ): SupportTicket @fdc_generated(from: "SupportTicket", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `User` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  user(
    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User @fdc_generated(from: "User", purpose: QUERY_SINGLE)
  """
  ✨ List `AppRule` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  appRules(
    """
    Filter condition to narrow down the query results.
    """
    where: AppRule_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [AppRule_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: AppRule_Having
  ): [AppRule!]! @fdc_generated(from: "AppRule", purpose: QUERY_MULTIPLE)
  """
  ✨ List `FriendRequest` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  friendRequests(
    """
    Filter condition to narrow down the query results.
    """
    where: FriendRequest_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [FriendRequest_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: FriendRequest_Having
  ): [FriendRequest!]! @fdc_generated(from: "FriendRequest", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Friendship` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  friendships(
    """
    Filter condition to narrow down the query results.
    """
    where: Friendship_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Friendship_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Friendship_Having
  ): [Friendship!]! @fdc_generated(from: "Friendship", purpose: QUERY_MULTIPLE)
  """
  ✨ List `InstalledApp` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  installedApps(
    """
    Filter condition to narrow down the query results.
    """
    where: InstalledApp_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [InstalledApp_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: InstalledApp_Having
  ): [InstalledApp!]! @fdc_generated(from: "InstalledApp", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Parent` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  parents(
    """
    Filter condition to narrow down the query results.
    """
    where: Parent_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Parent_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Parent_Having
  ): [Parent!]! @fdc_generated(from: "Parent", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Student` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  students(
    """
    Filter condition to narrow down the query results.
    """
    where: Student_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Student_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Student_Having
  ): [Student!]! @fdc_generated(from: "Student", purpose: QUERY_MULTIPLE)
  """
  ✨ List `StudentAvatar` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  studentAvatars(
    """
    Filter condition to narrow down the query results.
    """
    where: StudentAvatar_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [StudentAvatar_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: StudentAvatar_Having
  ): [StudentAvatar!]! @fdc_generated(from: "StudentAvatar", purpose: QUERY_MULTIPLE)
  """
  ✨ List `StudentConfig` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  studentConfigs(
    """
    Filter condition to narrow down the query results.
    """
    where: StudentConfig_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [StudentConfig_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: StudentConfig_Having
  ): [StudentConfig!]! @fdc_generated(from: "StudentConfig", purpose: QUERY_MULTIPLE)
  """
  ✨ List `StudentOwnedItem` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  studentOwnedItems(
    """
    Filter condition to narrow down the query results.
    """
    where: StudentOwnedItem_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [StudentOwnedItem_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: StudentOwnedItem_Having
  ): [StudentOwnedItem!]! @fdc_generated(from: "StudentOwnedItem", purpose: QUERY_MULTIPLE)
  """
  ✨ List `StudentSettings` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  studentSettingss(
    """
    Filter condition to narrow down the query results.
    """
    where: StudentSettings_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [StudentSettings_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: StudentSettings_Having
  ): [StudentSettings!]! @fdc_generated(from: "StudentSettings", purpose: QUERY_MULTIPLE)
  """
  ✨ List `SubjectProgress` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  subjectProgresses(
    """
    Filter condition to narrow down the query results.
    """
    where: SubjectProgress_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [SubjectProgress_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: SubjectProgress_Having
  ): [SubjectProgress!]! @fdc_generated(from: "SubjectProgress", purpose: QUERY_MULTIPLE)
  """
  ✨ List `SupportTicket` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  supportTickets(
    """
    Filter condition to narrow down the query results.
    """
    where: SupportTicket_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [SupportTicket_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: SupportTicket_Having
  ): [SupportTicket!]! @fdc_generated(from: "SupportTicket", purpose: QUERY_MULTIPLE)
  """
  ✨ List `User` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  users(
    """
    Filter condition to narrow down the query results.
    """
    where: User_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [User_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: User_Having
  ): [User!]! @fdc_generated(from: "User", purpose: QUERY_MULTIPLE)
}
