from pydantic import BaseModel, Field
from typing import List, Literal
from .models import QuestionSchema

class GenerateQuizResponse(BaseModel):
    quiz_session_id: str = Field(..., description="The ID of the generated quiz session")
    selected_subject_id: int = Field(..., description="The ID of the subject that was selected (either manually or automatically)")
    selected_subject_name: str = Field(..., description="The name of the selected subject")
    quiz_title: str
    questions: List[QuestionSchema]
    quiz_source: Literal["FRESH", "CACHED", "BANK"] = Field(
        default="FRESH",
        description=(
            "FRESH — generated by the LLM now. "
            "CACHED — returned from an existing unsubmitted session (cross-device reuse). "
            "BANK — assembled from the student's previously answered questions (LLM fallback)."
        )
    )

    # Allow extra fields in case the LLM returning structured data has a slightly different shape
    model_config = {"extra": "allow"}


class QuizSubmissionResponse(BaseModel):
    score: float
    total_questions: int
    feedback: str
