import re
import uuid
from pydantic import BaseModel, Field, field_validator
from typing import List, Optional, Literal

# Pre-compiled pattern for LaTeX delimiters and bare dollar signs.
# Strips: $...$ inline, \(...\) inline, \[...\] display blocks, and stray $.
_LATEX_PATTERN = re.compile(r"\$[^$]*\$|\\\([\s\S]*?\\\)|\\\[[\s\S]*?\\\]|\$")


def _strip_latex(text: str) -> str:
    """Remove LaTeX delimiters and reformat plain-text math."""
    if not text:
        return text
    return _LATEX_PATTERN.sub("", text).strip()


class GenerateQuizRequest(BaseModel):
    subject_id: Optional[int] = Field(
        None,
        description="The ID of the subject. If omitted, the system will auto-select the highest priority subject."
    )
    total_questions: int = Field(
        default=10, ge=1, le=50,
        description="Total number of questions to generate"
    )


class QuestionSchema(BaseModel):
    question_id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        description="Backend-generated unique ID. Ignore this field."
    )
    topic: str = Field(..., description="The name of the topic or skill this question belongs to")
    question_text: str
    options: List[str]
    correct_answer: str
    explanation: str
    difficulty: int = Field(..., ge=1, le=5, description="Difficulty level of the question from 1 to 5")
    hints: List[str] = Field(..., description="Exactly 3 progressive hints to help the student in Arabic")

    @field_validator("question_text", "explanation", mode="before")
    @classmethod
    def strip_latex_from_text(cls, v: str) -> str:
        """
        Enforce the plain-text math formatting rule at the schema level.
        The LLM prompt instructs Gemini not to use LaTeX, but this validator
        acts as a hard safety net in case the model still produces delimiters.
        """
        return _strip_latex(v)

    @field_validator("hints", mode="before")
    @classmethod
    def strip_latex_from_hints(cls, v: List[str]) -> List[str]:
        if not v:
            return v
        return [_strip_latex(h) for h in v]


class GenerateQuizResponse(BaseModel):
    quiz_session_id: str = Field(..., description="The ID of the generated quiz session")
    selected_subject_id: int = Field(..., description="The ID of the subject that was selected (either manually or automatically)")
    selected_subject_name: str = Field(..., description="The name of the selected subject")
    quiz_title: str
    questions: List[QuestionSchema]
    quiz_source: Literal["FRESH", "CACHED", "BANK"] = Field(
        default="FRESH",
        description=(
            "FRESH — generated by the LLM now. "
            "CACHED — returned from an existing unsubmitted session (cross-device reuse). "
            "BANK — assembled from the student's previously answered questions (LLM fallback)."
        )
    )

    # Allow extra fields in case the LLM returning structured data has a slightly different shape
    model_config = {"extra": "allow"}


class StudentAnswer(BaseModel):
    question_id: str
    selected_option: str
    time_taken_ms: int = Field(default=10000, ge=0, description="Time taken to answer in ms")
    hints_used: int = Field(default=0, description="Number of hints used")

    @field_validator("hints_used", mode="before")
    @classmethod
    def clamp_hints_used(cls, v) -> int:
        """
        Clamp hints_used to [0, 3]. The server defines 3 as the max number
        of hints per question. Client bugs may send out-of-range values;
        we silently clamp rather than reject the whole submission.
        """
        return min(max(int(v), 0), 3)


class QuizSubmissionRequest(BaseModel):
    quiz_session_id: str = Field(..., description="The ID of the generated quiz session")
    answers: List[StudentAnswer]
    client_local_date: Optional[str] = Field(None, description="Local date from client (YYYY-MM-DD)")


class QuizSubmissionResponse(BaseModel):
    score: float
    total_questions: int
    feedback: str
    rewards: Optional[dict] = None  # Gamification rewards summary
